# netlify.toml  (at repo root)
[build]
  base = "frontend"                 # build INSIDE the frontend folder
  command = "npm ci && npm run build"
  publish = "build"                 # CRA outputs to "build"

[[redirects]]                       # SPA fallback for React Router
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
